workflows:
  android-release:
    name: EMFAD2 Android Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        ANDROID_HOME: /opt/homebrew/share/android-commandlinetools
      java: 17

    scripts:
      - name: Environment Check
        script: |
          echo "=== Environment Check ==="
          java -version
          echo "Project files:"
          ls -la
          echo "App module:"
          ls -la app/

      - name: Install and Setup Gradle
        script: |
          echo "=== Installing Gradle ==="
          brew install gradle
          gradle --version
          
          echo "=== Creating Gradle Wrapper ==="
          gradle wrapper --gradle-version 8.0
          chmod +x gradlew
          
          echo "=== Testing Wrapper ==="
          ./gradlew --version

      - name: Build Release APK
        script: |
          echo "=== Building Release APK ==="
          ./gradlew clean
          ./gradlew assembleRelease --stacktrace

      - name: Find APK
        script: |
          echo "=== Finding APK Files ==="
          find . -name "*.apk" -type f
          
          if [ $(find . -name "*.apk" -type f | wc -l) -eq 0 ]; then
            echo "No APK found! Checking build structure..."
            find . -name "build" -type d
            find . -name "outputs" -type d
            exit 1
          else
            echo "APK found successfully!"
            find . -name "*.apk" -type f -exec ls -lh {} \;
          fi

    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/apk/debug/*.apk

  android-debug:
    name: EMFAD2 Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        ANDROID_HOME: /opt/homebrew/share/android-commandlinetools
      java: 17

    scripts:
      - name: Quick Build
        script: |
          echo "=== Quick Debug Build ==="
          brew install gradle
          gradle wrapper --gradle-version 8.0
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/apk/debug/*.apk
