workflows:
  android-release:
    name: EMFAD Android Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        ANDROID_HOME: /opt/homebrew/share/android-commandlinetools
      java: 17
      # Entfernt android_signing für unsigned APK

    scripts:
      - name: Setup und Prüfungen
        script: |
          echo "=== Environment Setup ==="
          echo "Java Version:"
          java -version
          echo "Android SDK:"
          echo $ANDROID_HOME
          echo "Current Directory:"
          pwd
          echo "Directory Contents:"
          ls -la
          echo "Checking for Android project structure:"
          find . -name "*.gradle" -type f | head -10
          find . -name "AndroidManifest.xml" -type f | head -5

      - name: Gradle Wrapper Setup
        script: |
          echo "=== Gradle Wrapper Setup ==="
          
          # Prüfe ob es sich um ein Standard Android-Projekt handelt
          if [ -f "app/build.gradle" ] && [ -f "build.gradle" ]; then
            echo "Standard Android-Projekt erkannt"
            
            # Erstelle Gradle Wrapper falls nicht vorhanden
            if [ ! -f "gradlew" ]; then
              echo "Erstelle Gradle Wrapper..."
              
              # Installiere Gradle falls nicht vorhanden
              if ! command -v gradle &> /dev/null; then
                echo "Installiere Gradle..."
                brew install gradle
              fi
              
              # Erstelle Wrapper basierend auf build.gradle Version
              GRADLE_VERSION=$(grep -o "gradle:[0-9.]*" build.gradle | cut -d: -f2 | head -1)
              if [ -z "$GRADLE_VERSION" ]; then
                GRADLE_VERSION="8.0"
              fi
              echo "Verwende Gradle Version: $GRADLE_VERSION"
              
              gradle wrapper --gradle-version $GRADLE_VERSION
            fi
            
            # Setze Ausführungsrechte
            chmod +x gradlew
            
            echo "Gradle Wrapper Setup abgeschlossen"
            ls -la gradlew*
            
          else
            echo "Fehler: Keine Standard Android-Projektstruktur gefunden!"
            echo "Erwartete Dateien:"
            echo "- app/build.gradle"
            echo "- build.gradle (root)"
            echo ""
            echo "Gefundene Dateien:"
            find . -name "*.gradle" -type f
            exit 1
          fi

      - name: Gradle Sync und Validation
        script: |
          echo "=== Gradle Sync und Validation ==="
          
          # Teste Gradle Wrapper
          echo "Teste Gradle Wrapper..."
          ./gradlew --version
          
          # Sync Projekt
          echo "Synchronisiere Projekt..."
          ./gradlew --refresh-dependencies
          
          # Zeige verfügbare Tasks
          echo "Verfügbare Tasks:"
          ./gradlew tasks --all | grep -E "(assemble|build)" | head -20

      - name: Gradle Clean
        script: |
          echo "=== Gradle Clean ==="
          ./gradlew clean

      - name: Gradle Build Release (Unsigned)
        script: |
          echo "=== Gradle Build Release (Unsigned) ==="
          
          # Build Release APK (unsigned)
          ./gradlew assembleRelease \
            -Pandroid.enableJetifier=true \
            -Pandroid.useAndroidX=true \
            --stacktrace \
            --info
          
          # Zeige Build-Ergebnisse
          echo "=== Build Results ==="
          find . -name "*.apk" -type f | head -10

      - name: Verify APK
        script: |
          echo "=== APK Verification ==="
          
          # Finde alle APK-Dateien
          APK_FILES=$(find . -name "*.apk" -type f)
          
          if [ -z "$APK_FILES" ]; then
            echo "Fehler: Keine APK-Dateien gefunden!"
            echo "Build-Output-Verzeichnisse:"
            find . -name "outputs" -type d
            find . -name "build" -type d | head -10
            exit 1
          fi
          
          echo "Gefundene APK-Dateien:"
          for apk in $APK_FILES; do
            echo "  $apk ($(du -h "$apk" | cut -f1))"
          done

      - name: Basic APK Testing
        script: |
          echo "=== Basic APK Testing ==="
          
          # Finde Release APK
          RELEASE_APK=$(find . -path "*/release/*.apk" -type f | head -1)
          
          if [ -n "$RELEASE_APK" ]; then
            echo "Testing APK: $RELEASE_APK"
            
            # APK Info mit aapt (falls verfügbar)
            if command -v aapt &> /dev/null; then
              echo "APK Package Info:"
              aapt dump badging "$RELEASE_APK" | head -5
            fi
            
            # Dateigröße prüfen
            APK_SIZE=$(stat -f%z "$RELEASE_APK" 2>/dev/null || stat -c%s "$RELEASE_APK" 2>/dev/null)
            echo "APK Size: $APK_SIZE bytes"
            
            # Mindestgröße prüfen (1MB = 1048576 bytes)
            if [ "$APK_SIZE" -lt 1048576 ]; then
              echo "Warning: APK seems unusually small (< 1MB)"
            else
              echo "APK size looks reasonable"
            fi
          else
            echo "No release APK found for testing"
          fi

    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/apk/debug/*.apk
      - "*/build/outputs/apk/**/*.apk"
      - build/reports/
      - app/build/reports/
      - "*/build/reports/"

  android-debug:
    name: EMFAD Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        ANDROID_HOME: /opt/homebrew/share/android-commandlinetools
      java: 17

    scripts:
      - name: Setup
        script: |
          echo "=== Debug Build Setup ==="
          java -version
          pwd
          ls -la

      - name: Create Gradle Wrapper
        script: |
          if [ ! -f "gradlew" ]; then
            brew install gradle
            gradle wrapper --gradle-version 8.0
          fi
          chmod +x gradlew

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace

      - name: Test Debug APK
        script: |
          echo "=== Debug APK Testing ==="
          DEBUG_APK=$(find . -path "*/debug/*.apk" -type f | head -1)
          if [ -n "$DEBUG_APK" ]; then
            echo "Debug APK found: $DEBUG_APK"
            APK_SIZE=$(stat -f%z "$DEBUG_APK" 2>/dev/null || stat -c%s "$DEBUG_APK" 2>/dev/null)
            echo "Debug APK Size: $APK_SIZE bytes"
          fi

    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - "*/build/outputs/apk/**/*.apk"

  # Neuer Workflow: Signed Release (optional)
  android-release-signed:
    name: EMFAD Android Release Build (Signed)
    max_build_duration: 120
    instance_type: mac_mini_m2
    when:
      branch: main  # Nur für main branch

    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        ANDROID_HOME: /opt/homebrew/share/android-commandlinetools
      java: 17
      android_signing:
        - keystore_reference  # Nur wenn Keystore konfiguriert ist

    scripts:
      - name: Setup
        script: |
          echo "=== Signed Release Build Setup ==="
          java -version

      - name: Create Gradle Wrapper
        script: |
          if [ ! -f "gradlew" ]; then
            brew install gradle
            gradle wrapper --gradle-version 8.0
          fi
          chmod +x gradlew

      - name: Build Signed Release
        script: |
          ./gradlew assembleRelease \
            -Pandroid.enableJetifier=true \
            -Pandroid.useAndroidX=true \
            --stacktrace

    artifacts:
      - app/build/outputs/apk/release/*.apk
