workflows:
  android-release:
    name: EMFAD2 Android Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        ANDROID_HOME: /opt/homebrew/share/android-commandlinetools
      java: 17

    scripts:
      - name: Environment Check
        script: |
          echo "=== Environment Check ==="
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
          echo "ANDROID_HOME: $ANDROID_HOME"
          echo "Project files:"
          ls -la
          echo "App module:"
          ls -la app/

      - name: Install and Setup Gradle
        script: |
          echo "=== Installing Gradle ==="
          brew install gradle
          gradle --version
          
          echo "=== Creating Gradle Wrapper ==="
          # Use Gradle 8.2 which is compatible with AGP 8.0.0
          gradle wrapper --gradle-version 8.2
          chmod +x gradlew
          
          echo "=== Testing Wrapper ==="
          ./gradlew --version

      - name: Validate Build Files
        script: |
          echo "=== Validating Build Configuration ==="
          echo "Checking build.gradle files..."
          if [ ! -f "build.gradle" ]; then
            echo "ERROR: Root build.gradle not found!"
            exit 1
          fi
          if [ ! -f "app/build.gradle" ]; then
            echo "ERROR: App build.gradle not found!"
            exit 1
          fi
          if [ ! -f "settings.gradle" ]; then
            echo "ERROR: settings.gradle not found!"
            exit 1
          fi
          echo "All build files present ✓"

      - name: Clean and Sync
        script: |
          echo "=== Cleaning Project ==="
          ./gradlew clean --stacktrace --info
          
          echo "=== Gradle Sync ==="
          ./gradlew tasks --all

      - name: Build Release APK
        script: |
          echo "=== Building Release APK ==="
          # Add more verbose logging
          ./gradlew assembleRelease \
            --stacktrace \
            --info \
            --no-daemon \
            --no-build-cache

      - name: Find and Verify APK
        script: |
          echo "=== Finding APK Files ==="
          find . -name "*.apk" -type f
          
          # More detailed search
          echo "=== Build directory contents ==="
          if [ -d "app/build" ]; then
            find app/build -type f -name "*.apk" -exec ls -lh {} \;
          else
            echo "app/build directory not found!"
            echo "Available directories:"
            find . -name "build" -type d
            exit 1
          fi
          
          if [ $(find . -name "*.apk" -type f | wc -l) -eq 0 ]; then
            echo "No APK found! Checking build structure..."
            echo "Build outputs structure:"
            find app/build -type d 2>/dev/null || echo "No build directory found"
            exit 1
          else
            echo "APK found successfully!"
            find . -name "*.apk" -type f -exec ls -lh {} \;
          fi

    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/apk/debug/*.apk

  android-debug:
    name: EMFAD2 Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        ANDROID_HOME: /opt/homebrew/share/android-commandlinetools
      java: 17

    scripts:
      - name: Quick Debug Build
        script: |
          echo "=== Quick Debug Build ==="
          brew install gradle
          gradle wrapper --gradle-version 8.2
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace --info

    artifacts:
      - app/build/outputs/apk/debug/*.apk
